default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: upload_development
test:
  <<: *default
  database: upload_test

production:
  <<: *default
  database: upload_production
  username: sample
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>
